- name: 'status: pending'
  color: e4e669
  description: 'More info is needed before deciding what to do'
  aliases: []
  
- name: 'status: todo'
  color: c5def5
  description: 'Planned but not started'
  aliases: []
  
- name: 'status: assigned'
  color: c5def5
  description: 'Responsibility for this has been assigned'
  aliases: []
  
- name: 'status: started'
  color: c5def5
  description: 'Work on this has begun'
  aliases: []
  
- name: 'status: ongoing'
  color: c5def5
  description: 'An issue that requires ongoing attention'
  aliases: [] 
    
- name: 'status: done'
  color: c5def5
  description: 'A solution has been implemented, but not yet confirmed'
  aliases: []

- name: 'status: waitlist'
  color: cfd3d7
  description: 'No time for this now, but maybe later'
  aliases: ['wontfix']


- name: 'type: bug'
  color: d73a4a
  description: 'Verified problems that need to be worked on'
  aliases: ['bug']

- name: 'type: chore'
  color: C5DEF5
  description: 'Clearly defined job that needs regular attention'
  aliases: []

- name: 'type: docs'
  color: C5DEF5
  description: "Documentation changes"
  aliases: ['documentation']

- name: 'type: feature'
  color: 0E8A16
  description: 'New feature or feature request'
  aliases: ['enhancement', 'type: enhancement']

- name: 'type: fix'
  color: 1D76DB
  description: 'Updates to existing functionalities'
  aliases: ['fix']

- name: 'type: not a bug'
  color: 0e8a16
  description: 'Reports that happen not be our fault'
  aliases: ['not a bug']

- name: 'type: question'
  color: d876e3
  description: 'Further information is requested'
  aliases: ['question']
  
