name: build and test
#generate redoc docs and publish to GH Pages
#also calls test.yml
on:
  push: #when changes are pushed to default branch for the file src/openapi.yml
    branches:
      - develop
    paths:
      - src/openapi.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: C02PFCP98A1
          slack-message: "build and test ${{github.ref_name}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: portman #generate and run postman tests
        uses: ./.github/workflows/portman.yml
    
      - name: build # generate redoc web page and JSON version of schema
        run: |
          npx  redoc-cli bundle src/openapi.yaml -o docs/index.html
          npx  @redocly/openapi-cli bundle --output=docs/assets/openapi.json src/openapi.yaml
          npx  @redocly/openapi-cli bundle --dereferenced --output=docs/assets/dereferenced.json src/openapi.yaml

      - name: Publish to GH-pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
          clean: false

      - name: Notify slack success
        if: success()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':white_check_mark: successfully completed building and deploying API docs at https://api.vcpr.org '
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify slack failure
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':red_circle: failed building and deploying API docs on ${{github.repository}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

