name: Manual Mayhem-API

on:
  workflow_dispatch:

jobs:

  mayhem_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get_auth_token
        run: |
          TOK=`curl -i 'https://test.vcpr.org/authenticate' -X POST  --data-raw 'username=testVOR&password=tVpass'` | grep  'x-auth-token:'
          echo "::set-output name=tag::$TOK"  
      - name: check token
        run: echo ${{steps.get_auth_token.outputs.tag}}        
      - name: Run Mayhem for API to check for vulnerabilities
        uses: ForAllSecure/mapi-action@v1
        with:
          mapi-token: ${{ secrets.MAPI_SECRET }}
          api-url: http://test.vcpr.org
          api-spec: src/openapi.yaml
          html-report: mapi.html
          run-args: |
            #todo get token
            --header-auth ${{steps.get_auth_token.outputs.token}} 
            # Do not fuzz the '/logout' endpoint
            --ignore-endpoint "/api/logout"
            # Treat all warnings as errors
            --warnaserror

      - name: Archive Mayhem for API report
        uses: actions/upload-artifact@v2
        with:
          name: mapi-report
          path: mapi.html
