name: Run Portman tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install newman
        run: |
          npm install -g newman newman-reporter-htmlextra newman-reporter-html
      - name: Newman CLI
        id: newmanCli
        continue-on-error: true
        run: |
          newman run "portman/postman.json" --environment "tests/postman_environment.json" --bail -r cli,htmlextra 
      - name: list files
        run: |
          ls 
          ls ./newman
      #collection and env sourced from https://github.com/allenheltondev/postman-contract-test-generator
      #a Postman meta-collection that uses postman scripts to generate tests on-the-fly from an OAS file

