name: Run Portman tests
on:
  workflow_dispatch:



jobs:

  portman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: generate and run tests using Postman's Newman
        uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMANKEY }}
          collection: portman/postman.json
          environment: tests/postman_environment.json
          envVar: '[{ "key": "env-TESTMOR_CREDENTIALS", "value": ${{ secrets.TESTMOR_CREDENTIALS }} }]'
      #collection and env sourced from https://github.com/allenheltondev/postman-contract-test-generator
      #a Postman meta-collection that uses postman scripts to generate tests on-the-fly from an OAS file

