name: Manual Portman

on:
  workflow_dispatch:

jobs:

  portman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: portman-env 
        run: |
          PORTMAN_POSTMAN_API_KEY=${{secrets.PORTMAN_POSTMAN}}
          echo $PORTMAN_POSTMAN_API_KEY
          npx @apideck/portman --cliOptionsFile ./portman/portman-options.json
      - name: commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit portman-generated postman collection with tests'
          add: 'portman/postman.json'
