name: Run Portman tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Newman
        run: |
          npx -p newman-reporter-htmlextra  newman run "portman/postman.json"  --environment "tests/postman_environment.json"  -r htmlextra
      - name: list files
        run: |
          ls 
          ls ./newman
      #collection and env sourced from https://github.com/allenheltondev/postman-contract-test-generator
      #a Postman meta-collection that uses postman scripts to generate tests on-the-fly from an OAS file

