name: Manual Portman

on:
  workflow_dispatch:

jobs:
  portman:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "C02PFCP98A1"
          slack-message: "creating automated API tests for ${{github.ref_name}} "
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Generate Postman tests
        id: runPortman
        run: |
          npx @apideck/portman --cliOptionsFile ./portman/MOR/portman-options.yml
          npx @apideck/portman --cliOptionsFile ./portman/VOR/portman-options.yml
          npx @apideck/portman --cliOptionsFile ./portman/SAOR/portman-options.yml
      - name: commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "commit portman-generated postman collection with tests"
          add: "portman/postman.json"
      - name: Install newman
        run: |
          npm install -g newman newman-reporter-htmlextra newman-reporter-html
      - name: run Newman on portman-postman tests
        id: newmanCli
        continue-on-error: false
        run: |
          newman run "portman/postman.json" --environment "./portman/postman-testVOR.env.json" -n 1 --folder VOR -r cli,htmlextra --reporter-htmlextra-export="./docs/automated-tests-vor.html"
      - name: Publish to GH-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
          clean: false

      - name: echoresults
        run: |
          echo ${{steps.newmanCli.conclusion }}
          echo ${{steps.newmanCli.outcome }}

      - name: Notify slack success
        if: ${{ success() && steps.newmanCli.conclusion == 'success' }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "C02PFCP98A1"
          slack-message: ":white_check_mark: API tests passed. See https://api.vcpr.org/automated-tests for report"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Notify slack with failed tests
        if: ${{ success() && steps.newmanCli.conclusion == 'failure' }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "C02PFCP98A1"
          slack-message: ":red_check_mark: some API tests FAILED. See https://api.vcpr.org/automated-tests for report"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Notify slack failure
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "C02PFCP98A1"
          slack-message: ":red_circle: API testing FAILED for ${{github.repository}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
