name: Run Portman tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install newman
        run: |
          npm install -g newman newman-reporter-htmlextra newman-reporter-html
      - name: Newman CLI
        id: newmanCli
        continue-on-error: true
        run: |
          newman run "portman/postman.json" --environment "tests/postman_environment.json" --bail -r cli,htmlextra --reporter-htmlextra-export="./docs/automated-tests.html"      
      - name: Publish to GH-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
          clean: false
  
