name: Generate docs
on:
  push:
    branches:
      - develop

jobs:

  serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #should increment version, maybe sed openapi.yaml
      # better yet, trigger on release and keep multiple release versions somehow ...

#      - name: Slack Notify start
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_COLOR: warning
#          SLACK_MESSAGE: 'STARTED: Build of Public  API pages'
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_FOOTER: ""
#          SLACK_USERNAME: Github Action
      - name: redoc-cli bundle
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle src/openapi.yaml -o docs/index.html '  

# if success
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs       



#      - name: Notify slack success
#        if: success()
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_MESSAGE: 'SUCCESS: Docker image ${{steps.set_dockerTag.outputs.tag}} created'
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_FOOTER: ""
#          SLACK_USERNAME: Github Action
#          SLACK_COLOR: ${{job.status}}
#
#      - name: Notify slack fail
#        if: failure()
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_COLOR: danger
#          SLACK_MESSAGE: 'FAILURE '
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_FOOTER: ""
#          SLACK_USERNAME: Github Action