name: Generate docs and publish to GH Pages
on:
  push:
    branches:
      - develop
    paths:
      - "src/**"

jobs:

  serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: "creating Redoc documentation on ${{github.ref_name}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: redoc-cli bundle
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle src/openapi.yaml -o docs/index.html '  

      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs       

      - name: Notify slack success
        if: success()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':white_check_mark: successfully completed building and deploying API docs on ${{github.repository}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify slack failure
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':red_circle: failed building and deploying API docs on ${{github.repository}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

