name: Bundle OAS, generate docs and publish to GH Pages
on:
  push: #when changes are pushed to default branch for any .yaml in  src/split including subdirectories
    branches:
      - develop
    paths:
      - src/split/**/*.yaml

jobs:

  serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: "bundle, generate docs, publish on ${{github.ref_name}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: bundle OAS  #to bundled OAS, not to be confused with bundle docs to generate html
        run: npx @redocly/openapi-cli bundle src/split/openapi.yaml --output src/openapi.yaml
      - name: commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'rebundle src/split to src/openapi.yaml '
          add: 'src/openapi.yaml'
      - name: create docs from OAS #ReDoc calls this "bundling" too, to html
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle src/openapi.yaml -o docs/index.html '  

      - name: Publish to GH-pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs       

      - name: Notify slack success
        if: success()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':white_check_mark: successfully completed building and deploying API docs on ${{github.repository}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify slack failure
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: 'C02PFCP98A1'
          slack-message: ':red_circle: failed building and deploying API docs on ${{github.repository}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

