name: Generate docs (manual)
on:
  workflow_dispatch:

jobs:

  serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: redoc-cli t
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: ''
      - name: redoc-cli bundle
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle openapi.yaml'        
      - name: redoc-cli serve
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'serve src/openapi.yaml'   
