name: Generate docs (manual)
on:
  workflow_dispatch:

jobs:

  serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2  
      - name: redoc-cli bundle
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle src/openapi.yaml'   
